on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: render-readme

permissions: read-all

jobs:
  render-rmarkdown:
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Set up pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            rmarkdown
        needs: check

      # Render README.md using rmarkdown
      - name: render-README-with-rmarkdown
        run: Rscript -e 'rmarkdown::render("README.Rmd", output_format = "md_document")'

      - name: commit-rendered-README
        run: |
          git add README.md man/figures/README-*
          git commit -m "Re-build README.md" || echo "No changes to commit"
          git push origin master || echo "No changes to commit"
